aspnetcorewebapp/Models/CalculadoraModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace aspnetcorewebapp.Models
{
    public class CalculadoraModel
    {
        public int Numero1 { get; set; }
        public int Numero2 { get; set; }
    }
}

aspnetcorewebapp/Models/ErrorViewModel.cs
using System;

namespace aspnetcorewebapp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

aspnetcorewebapp/Controllers/CalculadoraController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using aspnetcorewebapp.Models;

namespace aspnetcorewebapp.Controllers
{
    public class CalculadoraController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public CalculadoraController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        // Método Index
        public IActionResult Index()
        {
            return View();
        }

        // Feature 01
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Somar(CalculadoraModel model)
        {
            try
            {
                // Feature 01
                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError("ERROR: " + ex.Message);
                return View();
            }
        }

        // Feature 02
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Subtrair(CalculadoraModel model)
        {
            try
            {
                // Feature 02
                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError("ERROR: " + ex.Message);
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Dividir(CalculadoraModel model)
        {
            try
            {
                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError("ERROR: " + ex.Message);
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Multiplicar(CalculadoraModel model)
        {
            try
            {
                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError("ERROR: " + ex.Message);
                return View();
            }
        }

    }
}

aspnetcorewebapp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using aspnetcorewebapp.Models;

namespace aspnetcorewebapp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            //teste
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

aspnetcorewebapp/Views/Calculadora/Index.cshtml
@model aspnetcorewebapp.Models.CalculadoraModel

@{
    ViewData["Title"] = "Create";
}

<h4>Create</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Numero1" class="control-label"></label>
                <input asp-for="Numero1" class="form-control" />
                <span asp-validation-for="Numero1" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Numero2" class="control-label"></label>
                <input asp-for="Numero2" class="form-control" />
                <span asp-validation-for="Numero2" class="text-danger"></span>
            </div>

            <br>
            <div class="form-group">
                <a asp-action="Somar" class="btn btn-info">Somar</a>
                <a asp-action="Subtrair" class="btn btn-info">Subtrair</a>
                <a asp-action="Dividir" class="btn btn-info">Dividir</a>
                <a asp-action="Multiplicar" class="btn btn-info">Multiplicar</a>
            </div>
        </form>
    </div>
</div>

aspnetcorewebapp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

aspnetcorewebapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - aspnetcorewebapp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">aspnetcorewebapp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Index">Calculadora</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - aspnetcorewebapp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>